### ISSUE TITLE
send xray through email

### ISSUE THREAD

**Issue by RendyTan** [szarroug3/X-Ray_Calibre_Plugin#103]
Hi, is there any way to send the xray through email to the kindle?

**Comment by szarroug3** [comment]
No, sorry. It can't be sent because the plug-in has to put that files in a
different direction than where they would go if they were sent via email.
It also has to do some modifications to the book (to the ASIAN) for the
book to recognize the file. That can only be done through USB.

**Comment by RendyTan** [comment]
Ok. Thanks
