### ISSUE TITLE
Auto-creation of aliases should cope with "{honorific} {christian name}" where appropriate

### ISSUE THREAD

**Issue by stoduk** [szarroug3/X-Ray_Calibre_Plugin#29]
As discussed in #18 pull request - some code copied from the old plugin to the new was modified incorrectly (though by chance would work!).

in `fullname_to_possible_aliases`: `title in "Lord"` became`"lord" in title`

The intention was for the code to look like: `title in ["Lord", "Mr"]` - I just hadn't figured out for which honorifics it was valid to pair it with a christian name.  For Lord this seems quite common to do (probably also true for at least lower religious honorifics such as Father or Brother), opinions are mixed on Mr/Mrs/Miss/etc., while I'm sure any military title shouldn't be used with christian names (at least, it seems wrong to me, I could be wrong!).

**Comment by szarroug3** [comment]
I totally misunderstood what this was doing. I'll fix this along with adding a fix for titles like Sgt Major.

**Comment by szarroug3** [comment]
I don't think lord {firstname} is ever used even when it's religious. it's usually lord {lastname}. I haven't included lord in my list of religious honorifics that only use first name. i.e Father John Doe would be give us Father John but Lord John Doe would give us Lord Doe

**Comment by stoduk** [comment]
https://en.wikipedia.org/wiki/Lord_John_series

A series about Lord John Grey where he is referred to as Lord John even in
the series title :)

Similarly for Sir - you can find references to Sir Richard (Branson) in
real life, and Sir Leigh in Dan Brown's Da Vinci Code.

You can probably see why I was wondering whether a blacklist is better than
the whitelist I started with - I imagine most honorifics can be used with
christian names (both because most authors won't care about being perfectly
accurate, and because there doesn't seem to be a definitive ok/not ok
guide).

**Comment by szarroug3** [comment]
fixed in https://github.com/szarroug3/X-Ray_Calibre_Plugin/pull/31 -- somehow managed to mess up the fix statement

**Comment by szarroug3** [comment]
Maybe we should update it to just create both title first name and title
last name. If it isn't used, it won't hurt.

**Comment by stoduk** [comment]
Yes, more aliases seems better than less - as you say they'll only get used
if they are found in the book's text.  On top of that, the user can delete
any they don't like.
