### ISSUE TITLE
Spot aliases in Shelfari data (eg. Theodore "Theo" Decker)

### ISSUE THREAD

**Issue by stoduk** [szarroug3/X-Ray_Calibre_Plugin#37]
I've seen this sort of thing a couple of times now, probably worth handling.  The alias is in quotes in the middle of the name - just need to pull that out to use it as an alias, and then do the auto-alias stuff on what remains (ie. pull out "Theo" as alias and then auto-alias "Theodore Decker").  In this case we could arguably auto-alias "Theo Decker" as well, but I'm not sure that is isn't going to be generally true.

http://www.shelfari.com/books/35528681/The-Goldfinch

**Comment by szarroug3** [comment]
I don't think this is needed anymore -- Goodreads has aliases built-in
