### ISSUE TITLE
X-Ray Not Generated: Could not find amazon page :Shelfari  moved to Amazon

### ISSUE THREAD

**Issue by anishagarwal2502** [szarroug3/X-Ray_Calibre_Plugin#38]
Hey every time I'm getting this, I've checked with books having valid ASINs as well as the uuid ones as well
... but no luck

and when I tried to configure shelfari it says that it has moved to Goodreads...

06-14-2016 17:17:52 	Getting shelfari url... 

X-Ray Creation: 
	Books Failed: [Book Name] : Could not find amazon page

**Comment by szarroug3** [comment]
Sorry for the issues. We have an issue open already to move from shelfari. Please look at #4.
