### ISSUE TITLE
Book config's status isn't updated if temporary goodreads issue hit

### ISSUE THREAD

**Issue by stoduk** [szarroug3/X-Ray_Calibre_Plugin#42]
In Book config dialog, I hit some error from goodreads which appeared on the status line (not 100% sure what it was - it was too quick to be a web timeout).  I retried and it worked, but the status line wasn't updated - rather confusing!

**Comment by szarroug3** [comment]
I fixed this while adding the ASIN back in for #43 -- sorry I forgot there was actually an issue open for this one.
