### ISSUE TITLE
Goodreads Searching

### ISSUE THREAD

**Issue by szarroug3** [szarroug3/X-Ray_Calibre_Plugin#43]
Update the way goodreads searching works. In the case of A Christmas Carol - Charles Dickens, it gives us the wrong book. Putting just "A Christmas Carol" works. Maybe we search by title then filter the results by author or something. Maybe we need to bring back searching by ASIN?

**Comment by szarroug3** [comment]
The only way to get the ASIN is from Amazon. I saw that many people on MobileRead were complaining about the Amazon page not being found. After investigating, I found that some Amazon pages redirect you sometimes not only to a different page but to a different protocol (HTTPS or HTTP). HTTPConnection and HTTPSConnection don't handle that at all. They basically just tell you that you've been redirected and then you have to handle it yourself -- in the case of redirecting to a different protocol, we'd have to open a new connection altogether. I really want to keep keep-alive connections since I'm sure there are people who use this plugin on a huge list of books at once and having to open a connection everytime is very slow. I haven't been able to find any other good way to do keep-alive connections but we can look into this again.

**Comment by stoduk** [comment]
What fun!  http connections redirecting to https is quite common these days, but I'm not aware of seeing it go the other way.  Have you seen that?  If not, we could just use https for amazon as well, a quick test for "Ready Player One - Ernest Cline" suggests using https works.

Do you think this has appeared from a change amazon has made?  I'm assume this used to work for all books (ie. http connection throughout worked) and now doesn't work for all books.  But that is a massive assumption.

Also - the windows GUI forces people to have ASIN properly embedded in books (eg. using the 'Quality Check" plugin, after doing an amazon lookup).  This plugin made this unnecessary and worked so much better for it, so if we can avoid it great.  However, if we can't get it to work then we could always look to see if the ASIN is there (either in the Calibre DB or embedded in the mobi file) and use it if it is.

**Comment by szarroug3** [comment]
I don't think seen it go from https to http but I honestly don't remember.
I'm pretty sure this is a change Amazon made because I didn't see it or see
anyone complain about it before then all of sudden, many people complained
about it on MobileRead and then my books all started doing it too (even
ones that weren't doing it before). Also, yeah we can search the db for it.
I think Calibre adds the isbn on import.
