### ISSUE TITLE
There seems to be an issue updating the ASIN in mobi files.

### ISSUE THREAD

**Issue by szarroug3** [szarroug3/X-Ray_Calibre_Plugin#51]
As posted on MobileRead by Galunid:

Books Failed:
Throne of Glass - Sarah J. Maas:
MOBI: Unable to update ASIN in book on device.
AZW3: The book is not on the device.

My system is Ubuntu15.10 64 bit
Save me
By the way thanks for the plugin!

**Comment by szarroug3** [comment]
I haven't been able to reproduce this. @stoduk can you try so we can see if it's a linux issue? I assume it's not but just to be safe.

**Comment by stoduk** [comment]
Not seeing it, but not sure exactly what steps needed to reproduce it.  I've commented on the forum, hopefully we'll get more info from Galunid..

I wonder if they lack a thumbnail (we blindly try to rename it, which is reasonable as long as it should always be there!).

**Comment by Galunid** [comment]
My os specification
Linux krisXPS 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 14:46:51 UTC 2015 i686 i686 i686 GNU/Linux
Calibre version: 2.59
X-Ray version: 2.20
Kindle: Paperwhite 2(serial number: 9017) fw. 5.6.5
http://www.ibookpile.com/2015/01/throne-glass-series-sarah-j-maas.html
This is from where the book has been downloaded
It is the same for other books.
Just let me know if you need anything else

**Comment by szarroug3** [comment]
Do you have a cover image on the book on your Kindle?

**Comment by Galunid** [comment]
No, although it is in calibre

**Comment by szarroug3** [comment]
Ah, I think @stoduk is right about us blindly modifying an image that doesn't exist. I'm working on fixing it now. Thanks for the info!!

**Comment by Galunid** [comment]
After disabling book and resending books, the cover is back.

**Comment by szarroug3** [comment]
Does it work once you've added the cover back in?

**Comment by Galunid** [comment]
I've tested it.
The xray files and asin are proper, although  the cover image is gone :(
Any way to repair it?

**Comment by szarroug3** [comment]
Hm, I wonder if it's because the kindle downloaded the image.. Maybe it put
it in a different place?? Or maybe a different format? We'll have to look
into it..

**Comment by szarroug3** [comment]
I tested it and as far as I can see the cover image should be updated. I updated the ASIN, made sure the Kindle downloaded it, then created the x-ray. It took a few seconds for the Kindle to recognize the new filename but it did find it eventually.

**Comment by szarroug3** [comment]
Created a new issue for the image problem -- #53.
