### ISSUE TITLE
Book Meta Data used by plugin?

### ISSUE THREAD

**Issue by prenagha** [szarroug3/X-Ray_Calibre_Plugin#65]
Sorry if this is a dumb question but didn't see it stated anywhere... What meta data in Calibre is used to drive the various functions of this function?
Want to make sure I setup the meta data correctly so this all works.
In particular, what IDs, in what format, what keys...?

Thanks.

**Comment by szarroug3** [comment]
It requires the title and author be filled in. Everything else it needs, it will find on it's own if it doesn't already have it.

**Comment by prenagha** [comment]
Sometimes I will change (usually shorten) titles. Was wondering if the plugin will use the id meta data to locate the book. If so what format
`isbn:xxxx, amazon:yyyyy, asin:zzzz`
?

**Comment by szarroug3** [comment]
Ah yes, mobi-asin:xxxxxxxxxx should work.

**Comment by prenagha** [comment]
Thanks
