### ISSUE TITLE
Progress is stuck at "Unavailable" for the bulk of a job

### ISSUE THREAD

**Issue by stoduk** [szarroug3/X-Ray_Calibre_Plugin#69]
In Calibre's "Jobs" window, the Progress sits at "Unavailable" for an extended period - when processing a single book it prints that error for around 23s of the total 28s run time.

The problem is that the value being passed in to notifications.put() is zero.  Why Calibre doesn't treat this as 0% rather than some error case I don't know.  It should arguably be fixed in Calibre, but sometimes it is easier to just work around an API's quirks :)

Note: this is obviously just a cosmetic issue, and I don't know how many users will actually see it (do people normally open the Jobs window?).

A couple of possible fixes:
- Ask Kovid if he'll fix it :)

- Fudge the number passed through to notifications.get() so that it is always non-zero (I think it would have to be >= 1, as Calibre seems to be doing an integer conversion before comparing against zero "error" value)

**Comment by szarroug3** [comment]
Hey! You're back! Yeah I don't like it either. I wasn't sure what to do
about it.. Guess I can make it 1% or something.
