### ISSUE TITLE
Clean up code using pylint

### ISSUE THREAD

**Issue by szarroug3** [szarroug3/X-Ray_Calibre_Plugin#78]
title says it all.

**Comment by stoduk** [comment]
When are likely to commit this?  I imagine this will be a massive change, so I'd rather not be doing anything when this hits :)

**Comment by szarroug3** [comment]
Lol I've already started. You can see everything I've done so far in dev/pylint_fixes.  It is a massive change but I've been making sure to merge all the changes you've made along the way.. I can probably just go ahead and merge but by bit so that way it won't be so big of a merge.
