### ISSUE TITLE
Can I use this on Android?

### ISSUE THREAD

**Issue by yetanothernerdk** [szarroug3/X-Ray_Calibre_Plugin#81]
Can this xRay feature be used on Kindle App for Android?
If yes, How to use this?

**Comment by szarroug3** [comment]
From what I can see, Android's Kindle App does support X-Ray but our plugin
only sends files to Kindles. That being said, you can use the plugin to
make the files you need then copy them to your phone.

**Comment by ketanarlulkar** [comment]
Where do I copy the xray files, in which directory?

I have latest version of kindle android app, and I have copied mobi files into /storage/emulated/0/kindle/
Where should I copy XRAY.entities.<number>.asc file?

**Comment by szarroug3** [comment]
I believe they should go into the same folder as the book.. That's where
they are on my phone

**Comment by szarroug3** [comment]
Also, you need to make sure the ASIN of the book is the same as in the xray
filename

**Comment by ketanarlulkar** [comment]
This is what I have done:

1. Copied mobi file into /storage/emulated/0/kindle/ folder
2. Copied XRAY.entities.<ASIN>.asc into /storage/emulated/0/kindle/ folder
3. Then opened Kindle App.
4. I can see the book which I copied.
5. But when I opened the book, I didn't get any X-Ray option in it.

**Comment by szarroug3** [comment]
Did you check the other folder I mentioned?

**Comment by ketanarlulkar** [comment]
@szarroug3 My Kindle App data is in internal memory only.
So I have checked /storage/emulated/0/Android/data/com.amazon.kindle/files
There I have a folder for each book named as ASIN of that book.
Inside each folder, different number of files are there.
Some common files I have as follows:
*.ast
*.kfx
EndAction.data.<ASIN>.asc
XRAY.<ASIN>.<Some_Hash>.db
XRAY.<ASIN>.<Some_Hash>.db-journal

I have [this](https://www.amazon.in/Memoirs-Sherlock-Holmes-Wisehouse-Classics-ebook/dp/B01J8I9CQW) book in my kindle library.
This book has
Text-to-Speech: Enabled  
X-Ray: Enabled  
Word Wise: Enabled
Enhanced Typesetting: Enabled

The Folder for this book contains following:

![screenshot_20161106-103410](https://cloud.githubusercontent.com/assets/6256964/20035504/f7d62d8e-a40c-11e6-8bf4-b9f7f27ae094.png)

This plugin is creating XRAY.entities.<ASIN>.asc files.
But the folder has 
XRAY.<ASIN>.<Some_Hash>.db
XRAY.<ASIN>.<Some_Hash>.db-journal

**Comment by szarroug3** [comment]
Okay, I think the files need to go in the folder with the same ASIN.

**Comment by ketanarlulkar** [comment]
Really appreciate your help on this, but I have created <ASIN> folder inside it, and copied mobi file and XRAY file in it. But the app is not able to pick the book.

May be due to following

> This plugin is creating XRAY.entities.<ASIN>.asc files.
> But the folder has
> 
> ```
> XRAY.<ASIN>.<Some_Hash>.db
> XRAY.<ASIN>.<Some_Hash>.db-journal
> ```

**Comment by szarroug3** [comment]
No problem. I've actually tried doing it myself with and I can't seem to figure it out either :( Did your device automatically create that folder for you? Mine didn't even create that folder for books I've copied onto the device. It only created it for books that I got on Amazon and those already have X-Rays (X-Ray.<ASIN>.<Some_Hash>.db is the x-ray file.

**Comment by ketanarlulkar** [comment]
Same for me

>  Mine didn't even create that folder for books I've copied onto the device. It only created it for books that I got on Amazon and those already have X-Rays (X-Ray...db is the x-ray file.

**Comment by szarroug3** [comment]
I think you might have to find out how they get that hash value and then
use the same format. From what I can see the xray.<ASIN>.<Hash>.db file is
the x-ray file.

**Comment by ketanarlulkar** [comment]
I'm not sure how to do that.
Thanks for your help in understanding this.

**Comment by szarroug3** [comment]
No problem. I've tried googling to see if anyone else has been able to
figure it out. I can't seem to find anything. I can try to figure it out
myself but it might take a while. I'm juggling a few other things.

**Comment by yetanothernerdk** [comment]
@szarroug3 Any luck finding it? :blush:

**Comment by szarroug3** [comment]
Not yet. Sorry I've been working on some other things. I did try to look
into it but I haven't found anything yet. I haven't had too much time with
holidays and vacation.

**Comment by szarroug3** [comment]
@yetanothernerdk I just realized I missed one of your questions 

> BTW, How you figured it out for Kindle, i.e. what is name of X-ray file? where to store it? what should be the content of the X-ray file? How do you figured all of this?

For kindle, the plugin does all of that for your. The file name is XRAY.entities.<ASIN>.asc and the file goes into a folder with the book's name with the extension sdr. The folder should be in the same directory as your book. I.e if your book is located at directory_a/book.mobi, the xray file will be directory_a/book.sdr/XRAY.entities.<ASIN>.asc

I'm looking into Android now but I don't know if I'll be able to support it in the plugin anytime soon. It will require quite a bit of work since everything seems different on pc and mobile, [location of the files, filenames, etc. etc] but I'll continue looking into it in case you might able to do it manually.

**Comment by szarroug3** [comment]
I looked into this and I still can't seem to figure out how to name the file. 😞

**Comment by yetanothernerdk** [comment]
Is it working for Android?  How to use it?

**Comment by szarroug3** [comment]
No it's not. I couldn't figure out how to do it so I'm dropping the issue
for now.

**Comment by yetanothernerdk** [comment]
Oh, ok.
