### ISSUE TITLE
Cannot install plug-in

### ISSUE THREAD

**Issue by NudeSpoons** [szarroug3/X-Ray_Calibre_Plugin#88]
I am unable to install this plugin.  Here's the details of the error message I get:

```
calibre, version 2.76.0

ERROR: Plug-in installation failed:

A problem occurred while installing this plug-in.  This plug-in will now be uninstalled.
Please post the error message from the details below into the forum thread for this plug-in
and restart Calibre.

Traceback (most recent call last):
  File "site-packages\calibre\gui2\dialogs\plugin_updater.py", line 721, in _install_clicked
  File "site-packages\calibre\customize\ui.py", line 463, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 58, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 199, in load
  File "site-packages\calibre\customize\zipplugin.py", line 183, in load_module
  File "calibre_plugins.xray_creator.__init__", line 6, in <module>
ImportError: cannot import name __prefs__
```

Please advise what remedial action I might take.
Thank you.

**Comment by szarroug3** [comment]
I've heard some other people give me the same error. For now, it looks like uninstalling the plugin then reinstalling it has been working for other people. I'm looking into fixing it (more so now that I'm back from vacation). Thanks for your report! Please let me know if reinstalling works/doesn't work for you.

**Comment by szarroug3** [comment]
Also, what version of the plugin were you using before trying to update? Or were you installing for the first time?

**Comment by NudeSpoons** [comment]
I am installing for the first time.

**Comment by szarroug3** [comment]
hm, okay.. did you try reinstalling? Also, have you been trying to install by manually installing the zip or by searching in the "Get Plugins" section of Calibre.

**Comment by NudeSpoons** [comment]
I have worked it out for myself.  I was not running calibre as an Administrator (Windows 10).  Once I exited calibre and then ran it as an Administrator the plug-in installed without issue.  Thanks @szarroug3 for offering your help and advice - I appreciate it.

**Comment by szarroug3** [comment]
Glad you got it worked out. No problem. Hope you like the plugin! 😄
