### ISSUE TITLE
[Question] Using from Content Server

### ISSUE THREAD

**Issue by vswraith** [szarroug3/X-Ray_Calibre_Plugin#97]
How would I go about the Calibre Content server to send X-ray data to my kindle? 
I run Calibre on my NAS so the only way to get ebooks is via the Content Server. Any way to expose the X-ray files over it or maybe combine the X-ray file with the ebook?

**Comment by szarroug3** [comment]
So the plugin is not designed to work with the content server (I didn't even know it existed until you asked your question). I can tell you where the file get saved in the Calibre Library. If the book is at Calibre\{authorname}\{bookname}:

x-ray will be at: {bookname}\{bookname.sdr}\{filetype}\XRAY.entities.{ASIN}.asc
author profile, start/end actions will be at: {bookname}\non_xray\AuthorProfile.profile.{ASIN}.asc, {bookname}\non_xray\StartActions.profile.{ASIN}.asc, {bookname}\non_xray\EndActions.profile.{ASIN}.asc

How are you even running the process to create files in the first place?

**Comment by vswraith** [comment]
Using docker on my Synology nas to run calibre and all of its plugins. Really want X-ray but seems Content Server does not explose the .asc files  :( 
Any other way to get the files on my kindle wirelessly?

**Comment by szarroug3** [comment]
Sorry, there's no way to do it wirelessly. If you can run the command to create the files, you should be able to access the files through however you access files on your NAS regularly. You just have to figure out where your calibre library is and look in the folders I mentioned above. You'll have to manually copy them over to the correct folder on your kindle though.
