### ISSUE TITLE
Missing cover images

### ISSUE THREAD

**Issue by ottowayne** [szarroug3/X-Ray_Calibre_Plugin#99]
I am using Calibre 2.85.1 with the plugin version 3.0.6 on Windows 10.

After creating/updating the files with the plugin and then sending it to the device, the covers went away. I can fix this by converting the ebooks from EPUB to EPUB, but then X-Ray is gone again.

The only options I changed are the two overwrite options, because the X-Ray files didn't seem to get uploaded otherwise.

**Comment by szarroug3** [comment]
This is because the plugin updates the book's ASIN. Once you upload the
book to the Kindle, the Kindle updates the cover to whatever image they
have for that ASIN. You can get around this by going in the book's
preferences and giving the book a fake ASIN after the plugin has already
gotten it's Goodreads url.

**Comment by ottowayne** [comment]
Isn't there a way around this though?
Couldn't the plugin generate a fake ASIN?

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by szarroug3** [comment]
Yes but then it breaks other things. Putting in a fake ASIN in the book means I have to also put a fake ASIN in the the other files. Having a fake ASIN in those files breaks their functionality i.e when you hit mark as currently reading, it doesn't actually do it.

**Comment by szarroug3** [comment]
Note: my workaround above will also break the functionality of the other files. It's just the only way I can think of to get you your cover.

**Comment by ottowayne** [comment]
Okay, thanks for the answers.

**Comment by szarroug3** [comment]
Sure, sorry I couldn't get around it in a better way.
